config/routes.rb
Photogur::Application.routes.draw do

  resources :pictures
  root :to => "pictures#index"

  get 'index', to: 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	layout "main"

	def index
		@pictures = Picture.all.reverse
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

	def create
	# Make the variable @picture a new picture with the given params
			@picture = Picture.new(params[:picture])
		if @picture.save
		# if the save for the picture was successful, go to index.html.erb
			redirect_to pictures_url
		else
		# otherwise render the view associated with the action :new (i.e. new.html.erb)
			render :new
		end
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(params[:picture])
			redirect_to "/pictures/#{@picture.id}"
		else
			render :edit
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>smakT</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar">
      <div class="navbar-inner">
        <div class="container">
        	<div class="row-fluid show-grid">
          	<%= link_to "smakT", '/', class: "brand" %> 
          	<div class="offset10">
			<%= link_to "<button class='btn btn-success'>New Picture</button>".html_safe, "/pictures/new" %>
			</div>
			</div>
        </div>
      </div>
    </header>
    <div class="container" style="margin-top:55px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<!-- <div class="row">
	<div class="span offset5">
		<h2>
			<%= @pictures.length %> pictures
		</h2>
	</div>
</div> -->
<div class="row">
	<div class="span">
		<% @pictures.each do |picture| %>
		  <p><%= picture[:title] %> by <%= picture[:artist] %></p>
		  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
		<% end %>
	</div>
</div>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<br>
<div class="form-horizontal well">
<%= form_for @picture do |f| %>
  <p>
    <%= f.label "title" %>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "artist" %>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "url" %>
    <%= f.text_field "url" %>
  </p>
  <p>
    <div class="row">
      <div class="span">
    <%= submit_tag 'Save' , :class=> 'btn btn-success'%>
    </div>
    <div class="offset3">
    <%= link_to "Back to Pictures", pictures_url, class: "btn btn-warning" %>
    </div>
    </div>
  </p>
<% end %>
</div>

app/views/pictures/show.html.erb
<div class="row">
	<div class="span">
		<%= @picture[:title] %>, <%= @picture[:artist] %>
	</div>
	
</div>
<div class="row">
	<div class="span">
		<%= image_tag @picture.url %>
	</div>
</div>
<div class="row">
	<div class="span">
		<%= link_to "Back to Pictures", pictures_url, class: "btn btn-warning" %>
	</div>
	<div class="offset10">
	<%= link_to "Edit", edit_picture_path(@picture), class: "btn btn-primary" %><%= link_to "Delete", @picture, class: "btn btn-danger", :confirm => "Are you sure you want to delete this picture?", :method => :delete %>
	</div>
</div>